// The finished print shown as an "artifact": Preview / Code tabs, download,
// share. Used at the end of a session and for saved prints (#/p/<id>).

import { h } from '../core/dom.js';
import { download, fmtDate } from '../core/util.js';
import { sfx } from '../core/audio.js';
import { icon } from '../art/icons.js';
import { toast } from './ui.js';

const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c]);

// A playful "source" for the print, with light syntax colouring.
export function sourceFor(meta) {
  const lines = [
    `// ${meta.fileName} — generated by Claude 照相馆`,
    `import { Booth, Photo, Sticker } from 'claude-booth';`,
    ``,
    `export default function PhotoStrip() {`,
    `  return (`,
    `    <Booth model="${meta.model}" frame="${meta.frame}" filter="${meta.filter}" date="${meta.date}">`,
    ...meta.photos.map((p, i) => `      <Photo src="shot_${p.shot}.jpg" pose="${p.pose}" smile={${(0.93 + ((i * 7) % 6) / 100).toFixed(2)}} />`),
    ...(meta.stickers.length
      ? meta.stickers.slice(0, 12).map((s) => `      <Sticker name="${s}" />`)
      : [`      {/* 没贴贴纸，素颜也很好看 */}`]),
    ...(meta.stickers.length > 12 ? [`      {/* …还有 ${meta.stickers.length - 12} 个贴纸 */}`] : []),
    ...(meta.strokes ? [`      <Doodle strokes={${meta.strokes}} />`] : []),
    `    </Booth>`,
    `  );`,
    `}`,
  ];
  return lines
    .map((ln) =>
      esc(ln)
        .replace(/^(\s*\/\/.*)$/, '<i class="c">$1</i>')
        .replace(/(\{\/\*.*?\*\/\})/g, '<i class="c">$1</i>')
        .replace(/(&quot;.*?&quot;|'.*?')/g, '<i class="s">$1</i>')
        .replace(/\b(import|from|export|default|function|return)\b/g, '<i class="k">$1</i>')
        .replace(/(&lt;\/?)([A-Z]\w*)/g, '$1<i class="t">$2</i>'),
    )
    .map((ln, i) => `<span class="ln">${i + 1}</span>${ln}`)
    .join('\n');
}

export class ArtifactView {
  // rec: { blob, title, fileName, meta }
  constructor(rec, { onAgain, onDelete } = {}) {
    this.rec = rec;
    this.url = URL.createObjectURL(rec.blob);
    this.img = h('img.artifact-img', { src: this.url, alt: rec.title || '大头贴' });
    this.preview = h('div.artifact-preview', this.img);
    this.code = h('pre.artifact-code', { hidden: true });
    this.code.innerHTML = sourceFor(rec.meta);
    this.el = h('div.artifact', this.preview, this.code);

    const tabs = h('div.seg.artifact-tabs', { role: 'tablist' });
    const setTab = (id) => {
      for (const b of tabs.children) b.setAttribute('aria-checked', String(b.dataset.id === id));
      this.preview.hidden = id !== 'preview';
      this.code.hidden = id !== 'code';
    };
    for (const [id, label, ico] of [['preview', '预览', 'eye'], ['code', '代码', 'code']]) {
      const b = h('button.seg-opt', { type: 'button', role: 'tab', dataset: { id }, 'aria-label': label }, icon(ico, { size: 15 }), h('span.tab-label', label));
      b.addEventListener('click', () => {
        sfx.tick();
        setTab(id);
      });
      tabs.append(b);
    }
    setTab('preview');
    this.tabs = tabs;

    this.downloadBtn = h('button.icon-btn', { type: 'button', title: '下载 PNG', 'aria-label': '下载 PNG' }, icon('download'));
    this.downloadBtn.addEventListener('click', () => this.download());
    this.copyBtn = h('button.icon-btn', { type: 'button', title: '复制图片', 'aria-label': '复制图片' }, icon('copy'));
    this.copyBtn.addEventListener('click', () => this.copy());
    this.tools = [tabs, this.copyBtn, this.downloadBtn];
    this.onAgain = onAgain;
    this.onDelete = onDelete;
  }

  download() {
    download(this.rec.blob, this.rec.fileName);
    sfx.select();
    toast('已下载 ' + this.rec.fileName);
  }

  async copy() {
    try {
      await navigator.clipboard.write([new ClipboardItem({ 'image/png': this.rec.blob })]);
      toast('已复制到剪贴板');
    } catch {
      toast('这个浏览器不支持复制图片，可以用下载');
    }
  }

  async share() {
    const file = new File([this.rec.blob], this.rec.fileName, { type: 'image/png' });
    if (navigator.canShare?.({ files: [file] })) {
      try {
        await navigator.share({ files: [file], title: this.rec.title || 'Claude 大头贴' });
      } catch {
        /* cancelled */
      }
    } else this.download();
  }

  destroy() {
    URL.revokeObjectURL(this.url);
  }
}

// Web Share with files (mostly phones); elsewhere "share" would just download.
export function canShareFiles() {
  try {
    return !!navigator.canShare?.({ files: [new File([''], 'x.png', { type: 'image/png' })] });
  } catch {
    return false;
  }
}

export function fileNameFor(title, date = new Date()) {
  const safe = (title || '大头贴').replace(/[\\/:*?"<>|\s]+/g, '-').slice(0, 30);
  return `claude-booth-${fmtDate(date, '')}-${safe}.png`;
}
