// Machine ①: PHOTOMATIC — a 1960s-style chemical B&W booth.
// Offline reference (docs/research.md §四): 4 flashes, a few minutes of
// developing, a warm damp strip of 4 frames (2×8" in the US).

import { props, stickers, layouts, frames } from './art.js';

export default {
  id: 'classic',
  name: 'PHOTOMATIC',
  plate: 'PHOTOMATIC · 4 POSES',
  title: '复古黑白胶片机',
  kicker: 'SINCE 1965 · 4 POSES',
  tagline: '四次闪光，一条冒着热气的黑白长条',
  features: ['4 连拍竖条', '黑白 / 棕褐冲洗', '1 次重拍', '显影出片'],
  inspiration: '欧美化学显影照相亭（Auto-Photo / Photo-Me）',
  price: 2,
  badge: 'CLASSIC',
  screenText: '4 POSES',
  lang: 'zh-CN',
  voice: { pitch: 0.9, rate: 1 },
  colors: {
    body: '#9e1f1f',
    trim: '#d9dde2',
    accent: '#e8c170',
    curtain: '#6d1111',
    screen: '#1d1a17',
    screenText: '#f3e6c8',
    glow: '#ffd98a',
    btn: '#e8c170',
    btnText: '#1d1a17',
    card: 'rgba(243,230,200,0.06)',
    cardBorder: 'rgba(243,230,200,0.2)',
  },
  fonts: {
    display: '"Limelight", "Bungee", serif',
    ui: '"Special Elite", "ZCOOL KuaiLe", monospace',
    load: ['Limelight', 'Special Elite', 'Caveat', 'Rubik Mono One'],
  },
  bgm: { style: 'lounge', key: 57, prog: [0, 9, 2, 7] },
  lines: {
    attract: '四次闪光，一次成像。投币就能拍！',
    insert: '请投入两枚代币。',
    paid: '谢谢惠顾！',
    choose: '请选择相纸的样式。',
    camera: '请坐好，看镜子。',
    props: '箱子里有帽子、胡子和眼镜，随便戴。',
    ready: '看镜头上方的红灯，要开始了！',
    cheese: ['Cheese!', '别眨眼！'],
    done: '四张拍完了！',
    check: '看看照片，不满意可以重拍一张。',
    pick: '看看照片，不满意可以重拍一张。',
    retake: '好，再来一张！',
    filter: '选一种冲洗药水的色调。',
    decorate: '用白色墨水在照片上写点什么吧。',
    hurry: '时间快到了！',
    timeup: '时间到！',
    review: '确认没问题就开始冲洗。',
    print: '照片正在冲洗，请稍候。',
    bye: '照片出来了，小心拿，还有点湿！',
  },
  shoot: {
    shots: 4,
    firstCountdown: 5,
    countdown: 3,
    retakes: 1,
    poses: [
      { text: '看镜头，微笑', icon: '🙂', sub: 'SMILE' },
      { text: '侧过脸 45°', icon: '🎩', sub: 'PROFILE' },
      { text: '做个鬼脸！', icon: '😜', sub: 'SILLY' },
      { text: '靠在一起', icon: '💏', sub: 'CLOSER' },
    ],
  },
  selectTime: 45,
  prepTime: 90,
  pickTime: 60,
  filterTime: 40,
  decorateTime: 120,
  options: [
    {
      id: 'flash',
      title: '选择闪光',
      sub: 'FLASH',
      lead: '老式照相亭用的是很硬的闪光灯。',
      choices: [
        { id: 'hard', name: '经典硬闪', desc: '高反差，脸很亮，背景偏暗', icon: '⚡' },
        { id: 'soft', name: '柔和补光', desc: '更平均，皮肤更细腻', icon: '💡' },
      ],
      default: 'hard',
      time: 30,
    },
  ],
  sampleProps: ['fedora', 'mustache'],
  maxProps: 3,
  props,
  liveFx(session) {
    const hard = session.options.flash !== 'soft';
    return { flash: hard ? 0.5 : 0.1, smooth: hard ? 0.1 : 0.3 };
  },
  previewFx: { tone: 'mono', contrast: 1.2, curve: 0.2, grain: 0.2, vignette: 0.4 },
  filters: [
    { id: 'bw', name: '经典黑白', desc: '高反差 + 颗粒', fx: { tone: 'mono', contrast: 1.28, curve: 0.3, grain: 0.35, vignette: 0.5, fade: 0.04 } },
    { id: 'sepia', name: '复古棕褐', desc: '像老相册', fx: { tone: 'sepia', contrast: 1.15, curve: 0.2, grain: 0.3, vignette: 0.55, fade: 0.12 } },
    { id: 'cyan', name: '蓝晒', desc: '蓝色氰版', fx: { tone: 'cyan', contrast: 1.2, grain: 0.25, vignette: 0.4, fade: 0.06 } },
    { id: 'faded', name: '褪色彩色', desc: '70 年代彩色机', fx: { saturation: 0.6, fade: 0.35, temp: 0.3, contrast: 0.95, grain: 0.3, vignette: 0.45 } },
  ],
  layouts,
  frames,
  stickers,
  textStyles: [
    { name: '粉笔', font: '"Caveat", cursive', color: '#f7f3ea', outline: 0, chip: '#2a2622' },
    { name: '打字机', font: '"Special Elite", monospace', color: '#1f1b18', outline: 0.03, chip: '#f3efe6' },
    { name: '红墨水', font: '"Caveat", cursive', color: '#b3122a', outline: 0, chip: '#f3efe6' },
  ],
  phrases: ['forever', 'us ♥', '1965', '好朋友', '第一次约会', 'Cheese!'],
  pens: [
    { pen: 'chalk', name: '粉笔', width: 10 },
    { pen: 'solid', name: '墨水笔', width: 8 },
    { pen: 'double', name: '描边笔', width: 10 },
  ],
  penColors: ['#f7f3ea', '#1f1b18', '#b3122a', '#e8c170', '#3d5a80'],
  print: { kind: 'chemical', sheet: 'single', copies: 1, paperName: '黑白相纸长条', backColor: '#ece6d8' },
};
